    {{ HTML::style('http://fonts.googleapis.com/css?family=Open+Sans:400italic,400') }}
    {{ HTML::style('http://fonts.googleapis.com/css?family=Droid+Sans') }}
    {{ HTML::style('http://fonts.googleapis.com/css?family=Lobster') }}
    {{ HTML::style('assets/bootstrap/css/bootstrap.min.css') }}
    {{ HTML::style('assets/bootstrap-material-design/css/roboto.min.css') }}
    {{ HTML::style('assets/bootstrap-material-design/css/material-fullpalette.min.css') }}
    {{ HTML::style('assets/bootstrap-material-design/css/ripples.min.css') }}
    {{ HTML::style('assets/font-awesome/css/font-awesome.min.css') }}
    {{ HTML::style('assets/css/estilo.css') }}